export { Icon } from './Icon'
export type { IconProps } from './Icon'
export { IconProvider, useIconRegistry } from './IconProvider'
export type { IconProviderProps } from './IconProvider'
export { builtInIcons } from './builtin'
export { createIconRegistry, emptyIconRegistry, iconComponentName, resolveIcon } from './registry'
export type { HeroIcon, IconRegistry, IconSet, IconVariant } from './registry'
export { iconAliases } from './aliases'
