/**
 * Token build.
 *
 * Reads the DTCG token files in tokens/ and emits everything a consumer needs:
 *
 *   dist/tokens.css   CSS custom properties, :root + .dark. Framework-agnostic —
 *                     Blade, React, Vue and plain HTML all consume this one file.
 *   dist/theme.css    A Tailwind v4 @theme block mapping the same values onto
 *                     utility names, for projects using Tailwind.
 *   dist/tokens.js    ESM export, for anything that needs values in JS —
 *                     chart palettes being the obvious case.
 *   dist/tokens.json  The resolved tree, for tooling.
 *
 * The token files are plain DTCG, so they can move to Style Dictionary or a
 * Figma sync later without rewriting them. Dark values ride in
 * `$extensions["shipbytes.dark"]` on the same token as the light value, so the
 * two can never drift apart.
 *
 *   node scripts/build-tokens.mjs
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = join(ROOT, 'tokens');
const DIST = join(ROOT, 'dist');
const DARK_KEY = 'shipbytes.dark';

// ---------------------------------------------------------------- load

const files = (await readdir(TOKENS)).filter((f) => f.endsWith('.json')).sort();
const tree = {};

for (const f of files) {
    const json = JSON.parse(await readFile(join(TOKENS, f), 'utf8'));
    deepMerge(tree, json);
}

function deepMerge(target, source) {
    for (const [k, v] of Object.entries(source)) {
        if (v && typeof v === 'object' && !Array.isArray(v) && !k.startsWith('$')) {
            target[k] ??= {};
            deepMerge(target[k], v);
        } else {
            target[k] = v;
        }
    }
    return target;
}

// ---------------------------------------------------------------- flatten

const isToken = (n) => n && typeof n === 'object' && '$value' in n;

/** Walk the tree and collect every token with its dotted path. */
function flatten(node, path = [], out = []) {
    for (const [k, v] of Object.entries(node)) {
        if (k.startsWith('$')) continue;
        if (isToken(v)) out.push({ path: [...path, k], token: v });
        else if (v && typeof v === 'object') flatten(v, [...path, k], out);
    }
    return out;
}

const tokens = flatten(tree);
const byPath = new Map(tokens.map((t) => [t.path.join('.'), t.token]));

// ---------------------------------------------------------------- resolve

const REF = /\{([^}]+)\}/g;

/** Resolve {a.b.c} references, following chains. Throws on unknown or cyclic. */
function resolve(value, seen = new Set()) {
    if (typeof value === 'number') return value;
    if (typeof value !== 'string') return value;

    return value.replace(REF, (match, ref) => {
        if (seen.has(ref)) throw new Error(`cyclic token reference: ${ref}`);
        const target = byPath.get(ref);
        if (!target) throw new Error(`unknown token reference: {${ref}}`);
        return String(resolve(target.$value, new Set([...seen, ref])));
    });
}

/**
 * CSS custom-property name for a token path.
 *
 * Everything is prefixed `--ds-` so the raw token layer can never collide with
 * a host application's own variables, or with the Tailwind namespace that
 * theme.css maps onto it (`--color-surface: var(--ds-surface)` — without
 * distinct names that would be a self-reference).
 *
 *   color.zinc.500      -> --ds-color-zinc-500
 *   semantic.text-muted -> --ds-text-muted      (the `semantic` segment is the
 *                                                app-facing API, so it is implied)
 *   radius.base         -> --ds-radius
 */
function varName(path) {
    let p = path[0] === 'semantic' ? path.slice(1) : path;
    if (p[p.length - 1] === 'base') p = p.slice(0, -1);
    return `--ds-${p.join('-')}`;
}

// ---------------------------------------------------------------- emit

const banner = (what) =>
    `/**\n * ${what}\n *\n * GENERATED by scripts/build-tokens.mjs — do not edit.\n * Change the source in tokens/ and rebuild.\n */\n`;

// --- tokens.css ---------------------------------------------------

const lightLines = [];
const darkLines = [];

for (const { path, token } of tokens) {
    // Composite typography tokens expand into their parts.
    if (token.$type === 'typography' && typeof token.$value === 'object') {
        for (const [prop, val] of Object.entries(token.$value)) {
            const kebab = prop.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
            lightLines.push(`  ${varName([...path, kebab])}: ${resolve(val)};`);
        }
        continue;
    }

    lightLines.push(`  ${varName(path)}: ${resolve(token.$value)};`);

    const dark = token.$extensions?.[DARK_KEY];
    if (dark !== undefined) darkLines.push(`  ${varName(path)}: ${resolve(dark)};`);
}

const tokensCss = `${banner('Design tokens as CSS custom properties.')}
/*
  Dark mode is driven by a \`dark\` class on the root element, not the OS
  preference, so a theme toggle can override the system setting. The
  prefers-color-scheme block below only applies when nothing has been chosen
  explicitly — set \`class="light"\` to opt a subtree back out.
*/
:root {
${lightLines.join('\n')}
}

.dark {
${darkLines.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not(.light):not(.dark) {
${darkLines.map((l) => `  ${l}`).join('\n')}
  }
}
`;

// --- icon sizes the components ask for -----------------------------
//
// The icon component composes its class as `size-${size}` from a prop, so
// Tailwind's scanner never sees the finished class — it reads source text, and
// `size="4.5"` in a Blade tag is not the string `size-4.5`. Any size that is
// not ALSO written literally somewhere gets no rule, and the SVG expands to
// fill its container.
//
// So the list is derived from the components rather than guessed. Guessing is
// what shipped v0.1.1 with 3.5 but not 4.5, which is the size <x-ds::alert>
// actually uses.
const VIEWS = new URL('../resources/views/', import.meta.url);

async function bladeFiles(dir) {
    const out = [];
    for (const entry of await readdir(dir, { withFileTypes: true })) {
        const child = new URL(entry.name + (entry.isDirectory() ? '/' : ''), dir);
        if (entry.isDirectory()) out.push(...(await bladeFiles(child)));
        else if (entry.name.endsWith('.blade.php')) out.push(child);
    }
    return out;
}

// A base range so a CONSUMER can pass any ordinary size and have it work.
// Deriving only from this package's own usage would fix our components and
// still break `<x-ds::icon size="7" />` in someone else's view — their source
// says `size="7"`, which is not the string `size-7` either. Fifteen extra
// rules is a fair price for the prop meaning what it says.
const BASE_ICON_SIZES = ['3', '3.5', '4', '4.5', '5', '5.5', '6', '7', '8', '9', '10', '11', '12', '14', '16'];

const iconSizes = new Set(BASE_ICON_SIZES);
for (const file of await bladeFiles(VIEWS)) {
    const src = await readFile(file, 'utf8');
    for (const m of src.matchAll(/<x-ds::icon\b[^>]*?\bsize="([0-9.]+)"/g)) iconSizes.add(m[1]);
    // Sizes written literally are already scannable, but including them costs
    // one rule each and removes a whole class of "it worked because something
    // else happened to use it" bugs.
    for (const m of src.matchAll(/\bsize-([0-9]+(?:\.[0-9]+)?)\b/g)) iconSizes.add(m[1]);
}
const iconSizeList = [...iconSizes].sort((a, b) => Number(a) - Number(b));

// --- theme.css (Tailwind v4) --------------------------------------

const themeLines = [];
for (const { path, token } of tokens) {
    const [group] = path;

    if (group === 'color') {
        themeLines.push(`  --color-${path.slice(1).join('-')}: var(${varName(path)});`);
    } else if (group === 'semantic') {
        // Semantic colours map onto Tailwind's colour namespace so `bg-surface`,
        // `text-muted` and `border-border` all work as utilities. They point at
        // the custom property rather than the literal, so toggling the `dark`
        // class re-points every utility without generating a second set.
        themeLines.push(`  --color-${path.slice(1).join('-')}: var(${varName(path)});`);
    } else if (group === 'radius') {
        // Semantic keys only. v4 has no DEFAULT convention, and reusing
        // sm/md/lg/xl would overwrite Tailwind's scale with different values.
        themeLines.push(`  --radius-${path[1]}: var(${varName(path)});`);
    } else if (group === 'shadow') {
        themeLines.push(`  --shadow-${path[1]}: var(${varName(path)});`);
    } else if (group === 'font') {
        themeLines.push(`  --font-${path[1]}: var(${varName(path)});`);
    } else if (group === 'space') {
        // `space.page` must become `--spacing-page` so the utility is `p-page`,
        // not `p-space-page`.
        themeLines.push(`  --spacing-${path[1]}: var(${varName(path)});`);
    } else if (group === 'control') {
        themeLines.push(`  --spacing-control-${path[1]}: var(${varName(path)});`);
    } else if (group === 'text' && token.$type === 'typography') {
        themeLines.push(`  --text-${path[1]}: var(${varName([...path, 'font-size'])});`);
        themeLines.push(
            `  --text-${path[1]}--line-height: var(${varName([...path, 'line-height'])});`,
        );
        themeLines.push(
            `  --text-${path[1]}--font-weight: var(${varName([...path, 'font-weight'])});`,
        );
        if ('letterSpacing' in token.$value) {
            themeLines.push(
                `  --text-${path[1]}--letter-spacing: var(${varName([...path, 'letter-spacing'])});`,
            );
        }
        // textTransform has no Tailwind theme hook — it stays in tokens.css for
        // plain-CSS consumers, and Tailwind users pair the size with `uppercase`.
        if ('textTransform' in token.$value) {
            themeLines.push(
                `  /* ${path[1]}: also apply \`${token.$value.textTransform}\` */`,
            );
        }
    }
}

// Re-declare the semantic mappings inside .dark.
//
// This is not redundancy — it is the whole reason theme switching works.
// `--color-x: var(--ds-x)` on :root substitutes --ds-x AT :root, and the
// RESOLVED value is what inherits. A .dark ancestor changing --ds-x cannot
// retroactively change it. Repeating the identical mapping inside .dark forces
// a second substitution, this time against .dark's --ds-x.
//
// Without this every semantic utility silently keeps its light value while the
// raw --ds-* properties flip, so a page half-changes theme.
const themedVars = new Set(
    tokens
        .filter((t) => t.token.$extensions?.[DARK_KEY] !== undefined)
        .map((t) => varName(t.path)),
);
const semanticMappings = themeLines.filter((l) => {
    const m = l.match(/var\((--ds-[\w-]+)\)/);
    return m && themedVars.has(m[1]);
});

const darkRemap = `
.dark {
${semanticMappings.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not(.light):not(.dark) {
${semanticMappings.map((l) => `  ${l}`).join('\n')}
  }
}
`;

const themeCss = `${banner('Tailwind CSS v4 theme, mapping the tokens onto utility names.')}
/*
  Import AFTER tokens.css and after \`@import "tailwindcss"\`:

    @import "tailwindcss";
    @import "@shipbytes/design-tokens/tokens.css";
    @import "@shipbytes/design-tokens/theme.css";

  Semantic colours resolve through var(), so a \`dark\` class on <html> re-points
  every utility built on them without generating a second set of classes.
*/
@custom-variant dark (&:where(.dark, .dark *));

/*
  The icon component builds its class as \`size-\${size}\` from a prop, which
  Tailwind's scanner cannot see — it reads source text, and \`size="4.5"\` in a
  Blade tag is not the string \`size-4.5\`. Without this, an icon whose size is
  never ALSO written literally somewhere gets no rule at all and the SVG
  expands to fill its container.

  This list is DERIVED from the components (build-tokens.mjs scans them), not
  written by hand. Hand-written, it shipped 3.5 but not 4.5 — which is the size
  <x-ds::alert> uses, so every alert rendered a checkmark the height of the
  panel in any app that did not already use size-4.5 for something else.
*/
@source inline("size-{${iconSizeList.join(',')}}");

/*
  The notch padding the bottom nav depends on.

  This was used by <x-ds::bottom-nav> for two releases and DEFINED NOWHERE — not
  a Tailwind utility, not in tokens.css, not here. So the bar rendered flush to
  the bottom edge of the screen, and on a notched phone the home indicator sat
  over the last few pixels of every tab: the tabs looked completely normal and
  the bottom of each one did not respond to a tap.

  Same shape as the size-4.5 bug. A class with no rule behind it is not an
  error, it is just nothing, and nothing is what it did.

  env() falls back to 0px wherever there is no inset, so this costs nothing on a
  device that does not need it.
*/
@utility safe-area-bottom {
  padding-bottom: env(safe-area-inset-bottom, 0px);
}

@theme {
${themeLines.join('\n')}
}
${darkRemap}`;

// --- tokens.js / tokens.json --------------------------------------

const resolved = {};
for (const { path, token } of tokens) {
    let node = resolved;
    for (const k of path.slice(0, -1)) node = node[k] ??= {};
    const leaf = path[path.length - 1];
    const value =
        token.$type === 'typography' && typeof token.$value === 'object'
            ? Object.fromEntries(
                  Object.entries(token.$value).map(([k, v]) => [k, resolve(v)]),
              )
            : resolve(token.$value);

    const dark = token.$extensions?.[DARK_KEY];
    node[leaf] = dark !== undefined ? { light: value, dark: resolve(dark) } : value;
}

const tokensJs = `${banner('Design tokens as JS values.')}
// Colours that vary by theme are { light, dark } pairs; everything else is a
// plain value. Charts and other JS-driven visuals should read from here rather
// than repeating literals, which is how the six admin chart palettes drifted.

export const tokens = ${JSON.stringify(resolved, null, 2)};

export default tokens;
`;

// ---------------------------------------------------------------- write

await mkdir(DIST, { recursive: true });
await writeFile(join(DIST, 'tokens.css'), tokensCss);
await writeFile(join(DIST, 'theme.css'), themeCss);
await writeFile(join(DIST, 'tokens.js'), tokensJs);
await writeFile(join(DIST, 'tokens.json'), JSON.stringify(resolved, null, 2) + '\n');

console.log(`built from ${files.length} token files:`);
console.log(`  ${tokens.length} tokens`);
console.log(`  ${lightLines.length} custom properties, ${darkLines.length} dark overrides`);
console.log(`  ${themeLines.length} Tailwind theme entries`);
console.log(`  → dist/tokens.css, dist/theme.css, dist/tokens.js, dist/tokens.json`);
